export enum ActionType {
  CONNECT_WALLET = "CONNECT_WALLET",
  CONNECT_WALLET_SUCCESS = "CONNECT_WALLET_SUCCESS",
  CONNECT_WALLET_ERROR = "CONNECT_WALLET_ERROR",
  LB_FACTORY = "LB_FACTORY",
  SET_POOL_ADDRESS = "SET_POOL_ADDRESS",
  ACCOUNT_BALANCE = "ACCOUNT_BALANCE",
  YOU_OWE = "YOU_OWE",
}
