export enum ActionType {
  CURRENT_THEME = "CURRENT_THEME",
  CONNECT_WALLET = "CONNECT_WALLET",
  CONNECT_WALLET_SUCCESS = "CONNECT_WALLET_SUCCESS",
  CONNECT_WALLET_ERROR = "CONNECT_WALLET_ERROR",
  LB_FACTORY = "LB_FACTORY",
  SET_POOL_ADDRESS = "SET_POOL_ADDRESS",
  ACCOUNT_BALANCE = "ACCOUNT_BALANCE",
  YOU_OWE = "YOU_OWE",
  REDEEM_COLLATERAL_AMOUNT = "REDEEM_COLLATERAL_AMOUNT",
  REDEEM_COLLATERAL_AMOUNT_BASE = "REDEEM_COLLATERAL_AMOUNT_BASE",
  REDEEM_ACTION_SUCCESS = "REDEEM_ACTION_SUCCESS",
  REDEEM_ACTION_FAILED = "REDEEM_ACTION_FAILED",
}
